# Generated by Django 3.1.7 on 2021-05-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upright', '0002_auto_20210514_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ident',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
