# Generated by Django 3.1.7 on 2021-05-14 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upright', '0003_product_ident'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name_lower',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_upper',
        ),
    ]
