# Generated by Django 3.1.7 on 2021-05-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upright', '0004_auto_20210514_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='label',
            new_name='name_lower',
        ),
        migrations.AddField(
            model_name='product',
            name='name_upper',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
