# Generated by Django 3.1.7 on 2021-05-14 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upright', '0005_auto_20210514_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name_lower',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_upper',
        ),
    ]
