# Generated by Django 3.1.7 on 2021-05-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upright', '0006_auto_20210514_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='table',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
