# Generated by Django 3.1.7 on 2021-06-01 16:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upright', '0007_product_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
