# Generated by Django 3.1.7 on 2021-06-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upright', '0008_auto_20210601_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.TextField(),
        ),
    ]
