# Generated by Django 3.1.7 on 2021-06-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upright', '0009_auto_20210602_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(max_length=22),
        ),
    ]
